skip_branch_with_pr: true
image: Visual Studio 2019

install:
  - cinst gitversion.portable -y --version 4.0.0

platform: Any CPU

configuration: Release

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: false

before_build:
  - nuget restore Source/PropertyTools.AppVeyor.sln
  - gitversion /l console /output buildserver
  
build_script:
  - msbuild Source/PropertyTools.AppVeyor.sln /p:Version=%GitVersion_NuGetVersion%

artifacts:
  - path: '**/*.nupkg'
