version: 2015.1.{build}

environment:
  nuget_api_key:
    secure: kM3Kse+ivuuE5RVoe6dPdw+aguWx56K2YeXujGa9tMPQTms3lv7QxNpTLFMALYNa
      
install:
  - cinst LynxToolkit

platform: Any CPU

configuration: Release

before_build:
  - cmd: UpdateVersionNumbers /Version=%APPVEYOR_BUILD_VERSION% /Directory=Source /Dependency=PropertyTools /ReleaseNotesFile=release-notes.txt
  - nuget restore Source/PropertyTools.AppVeyor.sln

build:
  project: Source/PropertyTools.AppVeyor.sln
  verbosity: minimal

deploy_script:
  - cmd: mkdir Packages
  - cmd: NuGet pack Source\PropertyTools.Wpf\PropertyTools.Wpf.nuspec -OutputDirectory Packages
  - cmd: for %%G in (Packages\*.nupkg) do NuGet push %%G %nuget_api_key%  
artifacts:
  - path: Output
    name: PropertyTools-$(APPVEYOR_BUILD_VERSION)
    type: zip
